[project]
name = "openbuildings-app"
version = "0.1.0"
description = "Streamlit app for exploring building footprints from Google Earth Engine Open Buildings dataset"
authors = [
    {name = "belisards", email = "adrianobf@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.39.0",
    "folium>=0.18.0",
    "streamlit-folium>=0.23.1",
    "geojson>=3.1.0",
    "shapely>=2.0.6",
    "pyproj>=3.7.0",
    "ipython>=8.29.0",
    "tqdm>=4.66.6",
    "earthengine-api>=0.1.401",
]

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.5",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
